---
http_interactions:
- request:
    method: post
    uri: http://tpt2.dev.cwds.io:8084/rfa-1a-forms?token=null
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-type:
      - application/json
  response:
    status:
      code: 201
      message: 
    headers:
      date:
      - Thu, 06 Jul 2017 15:21:50 GMT
      content-type:
      - application/json
      content-length:
      - '78'
    body:
      encoding: UTF-8
      string: |-
        {
          "id" : 47,
          "is_initial_application" : false,
          "is_other_type" : false
        }
    http_version: 
  recorded_at: Thu, 06 Jul 2017 15:21:47 GMT
recorded_with: VCR 3.0.3
