# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs

  # config: config/webpack
  # manifest: manifest.json
  # node_modules: node_modules

  extensions:
    - .coffee
    - .erb
    - .js
    - .jsx
    - .js.erb
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default

  dev_server:
    host: 0.0.0.0
    port: 5080
    https: false

test:
  <<: *default

  public_output_path: packs-test

production:
  <<: *default
